---
settings:
  name: Astra Trident
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: trident-rn.html
  downlevel: true
  versions:
  - version-number: '23.04'
    url: "/trident-2304"
  - version-number: '25.06'
    url: "/trident"
  - version-number: '25.02'
    url: "/trident-2502"
  - version-number: '24.10'
    url: "/trident-2410"
  - version-number: '24.06'
    url: "/trident-2406"
  - version-number: '24.02'
    url: "/trident-2402"
  - version-number: '23.10'
    url: "/trident-2310"
  - version-number: '23.07'
    url: "/trident-2307"
  - version-number: '23.01'
    url: "/trident-2301"
  - version-number: '22.10'
    url: "/trident-2210"
  - version-number: '22.07'
    url: "/trident-2207"
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Astra Trident のドキュメント
    url: "/index.html"
  - title: リリースノート
    entries:
    - title: 新機能
      url: "/trident-rn.html"
    - title: 以前のバージョン
      url: "/earlier-versions.html"
  - section: trident-concepts
  - section: trident-get-started
  - section: trident-managing-k8s
  - section: trident-use
  - section: trident-docker
  - title: よくある質問です
    url: "/faq.html"
  - title: サポート
    url: "/get-help.html"
  - title: トラブルシューティング
    url: "/troubleshooting.html"
  - section: trident-reco
  - section: trident-reference
  - title: 法的通知
    url: "/legal-notices.html"
product-family:
  name: Astra
  repo: astra-family
